# Generated by Django 3.0.7 on 2020-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200627_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=200, null=True),
        ),
    ]
